# 1. Build stage
FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm ci

COPY tsconfig.json tsconfig.json
COPY src ./src
COPY db ./db
COPY controllers ./controllers
COPY utils ./utils
COPY middleware ./middleware
COPY routes ./routes
COPY validation ./validation
COPY app.ts app.ts
COPY router.ts router.ts

RUN npx tsc

# 2. Runtime stage
FROM node:20-alpine

WORKDIR /app
ENV NODE_ENV=production

COPY package*.json ./
RUN npm ci --omit=dev

COPY --from=builder /app/dist ./dist

# Expose app port
EXPOSE 3000

CMD ["node", "dist/app.js"]